zvirt:
  metrics:
    - host_boot_time
    - host_up
    - host_status
    - host_external_status
    - host_max_scheduling_memory_bytes
    - host_spm_status
    - host_update_available
    - host_reinstall_required
    - host_vm_active
    - host_vm_migrating
    - host_vm_total
    - host_cpu_cores
    - host_cpu_current_idle_percent
    - host_cpu_current_system_percent
    - host_cpu_current_user_percent
    - host_cpu_current_load_percent
    - host_cpu_core_idle_percent
    - host_cpu_core_system_percent
    - host_cpu_core_user_percent
    - host_cpu_core_load_percent
    - host_cpu_sockets
    - host_cpu_speed_hertz
    - host_cpu_threads
    - host_ksm_cpu_current_percent
    - host_hugepages_1048576_free
    - host_hugepages_1048576_total
    - host_hugepages_2048_free
    - host_hugepages_2048_total
    - host_anonymous_huge_pages
    - host_ksm_pages
    - host_ksm_state
    - host_memory_free_bytes
    - host_memory_installed_bytes
    - host_memory_shared_bytes
    - host_memory_total_bytes
    - host_memory_used_bytes
    - host_swap_free_bytes
    - host_swap_total_bytes
    - host_swap_used_bytes
    - host_network_status
    - host_network_data_current_rx_bps_bits_per_second
    - host_network_data_current_rx_bytes_per_second
    - host_network_data_current_tx_bps_bits_per_second
    - host_network_data_current_tx_bytes_per_second
    - host_network_data_rx_bytes_total
    - host_network_rx_offset
    - host_network_tx_offset
    - host_network_data_tx_bytes_total
    - host_network_errors_rx_total
    - host_network_errors_tx_total
    - host_network_usage_percent
    - storage_total_bytes
    - storage_available_bytes
    - storage_committed_bytes
    - storage_master
    - storage_up
    - storage_status
    - storage_external_status
    - storage_used_bytes
    - storage_read_rate
    - storage_read_latency
    - storage_write_rate
    - storage_write_latency
    - storage_read_ops
    - storage_write_ops
    - storage_block_size
    - disk_size_bytes
    - disk_actual_size_bytes
    - disk_read_rate
    - disk_read_ops
    - disk_read_latency
    - disk_write_rate
    - disk_write_ops
    - disk_write_latency
    - disk_flush_latency
    - disk_vms_count
    - vm_boot_time
    - vm_up
    - vm_status
    - vm_elapsed_time
    - vm_migration_progress
    - vm_cpus
    - vm_cpu_cores
    - vm_cpu_threads
    - vm_cpu_sockets
    - vm_cpu_current_guest
    - vm_cpu_current_hypervisor
    - vm_cpu_current_total
    - vm_memory_installed
    - vm_memory_used
    - vm_memory_free
    - vm_memory_buffered
    - vm_memory_cached
    - vm_memory_unused
    - vm_network_current_total
    - vm_network_status
    - vm_network_data_current_rx_bps_bits_per_second
    - vm_network_data_current_rx_bytes_per_second
    - vm_network_data_current_tx_bps_bits_per_second
    - vm_network_data_current_tx_bytes_per_second
    - vm_network_data_rx_bytes_total
    - vm_network_rx_offset
    - vm_network_tx_offset
    - vm_network_data_tx_bytes_total
    - vm_network_errors_rx_total
    - vm_network_errors_tx_total
    - vm_disk_actual_size_bytes
    - vm_disk_read_rate
    - vm_disk_read_ops
    - vm_disk_read_latency
    - vm_disk_write_rate
    - vm_disk_write_ops
    - vm_disk_write_latency
    - vm_disk_flush_latency
    - vm_guest_disk_used
    - vm_guest_disk_free
    - vm_guest_disk_total
    - dc_up
    - cluster_up

  
  jobs:
    - zvirt-metrics
    - virt-exporter
  
  step: 30m
  
  hours: 2

  start_date: 2025-11-15
  end_date: 2025-11-22
  
